export const TOOL_NAMES = {
    SEARCH_NOTES_SEMANTIC: "search_notes_semantic",
    REFRESH_SEMANTIC_INDEX: "refresh_semantic_index",
    GET_ACTIVE_CONTEXT: "get_active_context",
    INSERT_AT_CURSOR: "insert_at_cursor",
    REPLACE_RANGE: "replace_range",
    LIST_NOTES: "list_notes",
    MOVE_NOTE: "move_note",
    GET_INDEX_STATUS: "get_index_status",
    CREATE_NOTE: "create_note",
    GET_NOTE: "get_note",
    UPDATE_NOTE_CONTENT: "update_note_content",
    DELETE_NOTE: "delete_note",
    UPDATE_NOTE_METADATA: "update_note_metadata",
} as const;

export const TOOL_NAME_LIST = [
    TOOL_NAMES.SEARCH_NOTES_SEMANTIC,
    TOOL_NAMES.REFRESH_SEMANTIC_INDEX,
    TOOL_NAMES.GET_ACTIVE_CONTEXT,
    TOOL_NAMES.INSERT_AT_CURSOR,
    TOOL_NAMES.REPLACE_RANGE,
    TOOL_NAMES.LIST_NOTES,
    TOOL_NAMES.MOVE_NOTE,
    TOOL_NAMES.GET_INDEX_STATUS,
    TOOL_NAMES.CREATE_NOTE,
    TOOL_NAMES.GET_NOTE,
    TOOL_NAMES.UPDATE_NOTE_CONTENT,
    TOOL_NAMES.DELETE_NOTE,
    TOOL_NAMES.UPDATE_NOTE_METADATA,
];
