export const TOOL_NAMES = {
  SEARCH_NOTES: "search_notes",
  SEMANTIC_SEARCH_NOTES: "semantic_search_notes",
  REFRESH_SEMANTIC_INDEX: "refresh_semantic_index",
  READ_NOTE: "read_note",
  READ_ACTIVE_CONTEXT: "read_active_context",
  EDIT_NOTE: "edit_note",
  LIST_NOTES: "list_notes",
  MOVE_NOTE: "move_note",
  GET_SEMANTIC_INDEX_STATUS: "get_semantic_index_status",
  CREATE_NOTE: "create_note",
  DELETE_NOTE: "delete_note",
  PATCH_NOTE_METADATA: "patch_note_metadata",
} as const;

export const TOOL_NAME_LIST = [
  TOOL_NAMES.SEARCH_NOTES,
  TOOL_NAMES.SEMANTIC_SEARCH_NOTES,
  TOOL_NAMES.REFRESH_SEMANTIC_INDEX,
  TOOL_NAMES.READ_NOTE,
  TOOL_NAMES.READ_ACTIVE_CONTEXT,
  TOOL_NAMES.EDIT_NOTE,
  TOOL_NAMES.LIST_NOTES,
  TOOL_NAMES.MOVE_NOTE,
  TOOL_NAMES.GET_SEMANTIC_INDEX_STATUS,
  TOOL_NAMES.CREATE_NOTE,
  TOOL_NAMES.DELETE_NOTE,
  TOOL_NAMES.PATCH_NOTE_METADATA,
];
